# Site settings
title: Patrick O'Donnell (from _config.yml)
email: patrick.bouke.odonnell@gmail.com (from _config.yml)
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# twitter_username: 
# github_username: caedmon5

# Build settings
markdown: kramdown
